/**
 * PLACEHOLDER LEGAL CONTENT — REPLACE WITH LAWYER-REVIEWED VERSION.
 * UK-specific (Consumer Rights Act 2015, GDPR + UK DPA 2018,
 * Consumer Contracts Regulations 2013, CDPA 1988). Provided here as a
 * compliance scaffolding so the T&C gate is non-empty during development.
 */
export const TC_VERSION = "1.0";

export interface LegalSection { h: string; p: string }

export const TERMS_CONTENT: { title: string; intro: string; sections: LegalSection[] } = {
  title: "Terms & Conditions",
  intro:
    "Welcome to Revoloai. These Terms govern your use of our AI career assistant. " +
    "By using Revoloai you agree to be bound by these Terms. If you do not agree, " +
    "please do not use the service.",
  sections: [
    { h: "1. About Revoloai", p: "Revoloai is a UK-based AI career assistant providing job search, interview coaching and career guidance powered by artificial intelligence. The service is operated by Revoloai Ltd, registered in England and Wales." },
    { h: "2. Acceptance of Terms", p: "By creating an account, completing onboarding, or paying for any service, you confirm that you are at least 18 years old and you accept these Terms and our Privacy Policy in full. Acceptance is recorded with a timestamp and the current Terms version." },
    { h: "3. Description of Service", p: "Revoloai provides AI-generated career guidance, CV feedback, interview practice and job matching. Job listings are sourced from third-party providers (Adzuna). Chat replies are generated by large language models (Anthropic Claude). All AI outputs are guidance only and may contain errors or omissions." },
    { h: "4. User Obligations", p: "You agree to provide accurate information in your profile, to use Revoloai for personal career development only, not to upload illegal, harmful or infringing content, not to attempt to reverse engineer or scrape the service, and not to use AI outputs to train competing AI models." },
    { h: "5. AI Content Disclaimer", p: "AI-generated content is produced by automated systems and may be inaccurate, outdated, or unsuitable for your circumstances. Revoloai makes NO guarantee of employment, interviews, job offers, or any specific career outcome. You are responsible for verifying any information before acting on it." },
    { h: "6. Payments & Refunds (UK Consumer Rights Act 2015)", p: "Paid services are digital content delivered immediately. Under the Consumer Contracts Regulations 2013 you have a 14-day right to cancel ONLY IF the service has not been started. By paying you expressly agree the service may start immediately and you waive the 14-day cooling-off period once delivery begins." },
    { h: "7. Limitation of Liability", p: "To the maximum extent permitted by law, Revoloai's total liability for any claim is limited to the amount you paid for the specific service that gave rise to the claim. Revoloai is not liable for indirect, incidental, or consequential loss including loss of employment, loss of income, or loss of opportunity." },
    { h: "8. Intellectual Property", p: "All software, design, AI prompt templates, the Revoloai name, and the avatar character names (Maya, Sofia, Aria) are protected under the UK Copyright, Designs and Patents Act 1988 and applicable trademark law. AI outputs are licensed to you for personal, non-commercial use only. Redistribution, scraping, or commercial reuse is prohibited." },
    { h: "9. Privacy & Data Protection", p: "Revoloai processes personal data in accordance with UK GDPR and the Data Protection Act 2018. See our Privacy Policy for details on data we collect, how we use it, your rights, and how to exercise them." },
    { h: "10. Termination", p: "Revoloai may suspend or terminate accounts that violate these Terms. You may delete your account at any time via the data deletion page. Outstanding payments are not refunded for completed services." },
    { h: "11. Changes to Terms", p: "We may update these Terms. Material changes will increment the version number and require re-acceptance the next time you open the app. Continued use after a non-material update constitutes acceptance." },
    { h: "12. Governing Law", p: "These Terms are governed by the laws of England and Wales. Disputes are subject to the exclusive jurisdiction of the English courts, except where mandatory consumer law provides otherwise." },
    { h: "13. Contact", p: "Questions: legal@revoloai.com. Postal address: Revoloai Ltd, London, United Kingdom." },
  ],
};

export const PRIVACY_CONTENT: { title: string; intro: string; sections: LegalSection[] } = {
  title: "Privacy Policy",
  intro:
    "This Privacy Policy explains how Revoloai Ltd (\"we\", \"us\") collects, uses and protects your personal data under UK GDPR and the Data Protection Act 2018.",
  sections: [
    { h: "1. Data Controller", p: "Revoloai Ltd, England and Wales, is the data controller. Contact: privacy@revoloai.com." },
    { h: "2. Data We Collect", p: "Account: email, name, password hash. Profile (provided by you): target role, location, salary expectations, skills, experience. Usage: chat transcripts with Maya/Sofia/Aria, saved jobs, purchases. Technical: timestamps, error logs (no IP retention beyond 7 days)." },
    { h: "3. Why We Process It (Lawful Basis)", p: "Performance of contract (delivering the service you paid for); legitimate interest (improving the service, fraud prevention); your explicit consent (chat with AI, optional voice features); legal obligation (tax records, regulatory)." },
    { h: "4. AI Processing", p: "Chat messages are sent to Anthropic (Claude) for AI response generation. Job queries are sent to Adzuna (job listings provider). Payments are processed by Stripe. These providers act as processors under contract and do not retain content for their own purposes." },
    { h: "5. Your Rights (UK GDPR)", p: "Access \u2014 request a copy of your data. Rectification \u2014 correct inaccurate data. Erasure \u2014 delete your account and data. Restriction \u2014 limit processing. Portability \u2014 export your data. Objection \u2014 to legitimate-interest processing. Withdraw consent \u2014 at any time. Complain to the ICO (ico.org.uk)." },
    { h: "6. Retention", p: "Account data retained while the account is active. Deleted accounts purged within 30 days. Payment records retained 6 years for HMRC compliance." },
    { h: "7. Cookies", p: "We use essential cookies (auth, session). No third-party advertising cookies. See the Cookies page for details." },
    { h: "8. International Transfers", p: "Some processors (Anthropic, Stripe) operate in the US under UK adequacy decisions or Standard Contractual Clauses approved by the ICO." },
    { h: "9. Children", p: "Revoloai is not intended for users under 18." },
    { h: "10. Contact & Complaints", p: "privacy@revoloai.com. You may also lodge a complaint with the Information Commissioner's Office (ICO) at ico.org.uk." },
  ],
};

export const COPYRIGHT_CONTENT: { title: string; intro: string; sections: LegalSection[] } = {
  title: "Copyright & Intellectual Property",
  intro:
    "\u00a9 2026 Revoloai Ltd. All rights reserved. The Revoloai service, software, branding, and AI outputs are protected under the UK Copyright, Designs and Patents Act 1988 and applicable trademark law.",
  sections: [
    { h: "Trademarks", p: "\"Revoloai\" and the avatar character names \"Maya\", \"Sofia\" and \"Aria\" are trademarks of Revoloai Ltd in the United Kingdom and other jurisdictions. Use of these names in connection with similar services is prohibited without written permission." },
    { h: "Protected Content", p: "All AI-generated outputs (chat replies, interview questions, scoring, CV feedback, job match explanations) are the intellectual property of Revoloai and licensed to you under a personal, non-transferable, non-commercial licence." },
    { h: "Prohibited Uses", p: "You may NOT (a) scrape, mass-download, or systematically copy Revoloai content; (b) reproduce or redistribute AI outputs publicly or commercially; (c) use Revoloai outputs to train, fine-tune, evaluate, or benchmark competing AI models; (d) use the Maya, Sofia, or Aria personas in any third-party product." },
    { h: "Permitted Uses", p: "You MAY (a) use AI outputs for personal career development; (b) save and locally store CV feedback for your own use; (c) practise interview answers privately; (d) quote short excerpts for personal reference with attribution to Revoloai." },
    { h: "Reporting Infringement", p: "To report copyright infringement or request a licence, contact legal@revoloai.com with the subject line \"IP Notice\". Include the work concerned, your contact details, and a good-faith statement." },
  ],
};
